sonar.projectKey=sis-bem-estar
sonar.projectName=sis-bem-estar
sonar.projectVersion=1.0
sonar.host.url=http://192.168.53.231:9000

sonar.sourceEncoding=UTF-8
sonar.sources=backend,frontend/src
sonar.tests=backend/tests

sonar.python.version=3.12

sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**,**/.venv/**,**/venv/**,**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,backend/migrations/**,backend/tests/**,frontend/src/vite-env.d.ts

sonar.coverage.exclusions=manage.py,database/**,docker/**,docs/**,load_tests/**,backend/migrations/**,backend/core/asgi.py,backend/core/wsgi.py,frontend/src/vite-env.d.ts
sonar.cpd.exclusions=backend/migrations/**
