# Generated by Django 4.2.29 on 2026-03-12 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('matricula', models.CharField(blank=True, max_length=50, verbose_name='Matrícula')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('is_admin', models.BooleanField(default=False, verbose_name='É administrador?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('massagem', 'Massagem'), ('yoga', 'Yoga'), ('meditacao', 'Meditação'), ('nutricao', 'Nutrição'), ('pilates', 'Pilates'), ('acupuntura', 'Acupuntura'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('nome_profissional', models.CharField(blank=True, max_length=200, verbose_name='Nome do profissional')),
                ('data', models.DateField(verbose_name='Data do evento')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de término')),
                ('duracao_sessao', models.PositiveIntegerField(verbose_name='Duração de cada sessão (minutos)')),
                ('capacidade_por_horario', models.PositiveIntegerField(default=1, verbose_name='Capacidade por horário')),
                ('imagem_url', models.URLField(blank=True, verbose_name='URL da imagem')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado'), ('encerrado', 'Encerrado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('corpo_email', models.TextField(blank=True, help_text='Variáveis disponíveis: {nome}, {titulo}, {data}, {hora_inicio}, {hora_fim}, {link}, {chave}', verbose_name='Corpo do e-mail')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Início')),
                ('hora_fim', models.TimeField(verbose_name='Término')),
                ('vagas_disponiveis', models.PositiveIntegerField(default=1, verbose_name='Vagas disponíveis')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='backend.evento')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ConviteEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de acesso')),
                ('chave_mensagem', models.CharField(editable=False, max_length=8, verbose_name='Chave de mensagem')),
                ('usado', models.BooleanField(default=False, verbose_name='Link já utilizado')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='backend.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Convite de E-mail',
                'verbose_name_plural': 'Convites de E-mail',
                'unique_together': {('usuario', 'evento')},
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='confirmado', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('convite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamento', to='backend.conviteemail')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='backend.horario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-criado_em'],
                'unique_together': {('usuario', 'horario')},
            },
        ),
    ]
