# Generated by Django 4.2.29 on 2026-03-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_evento_emails_enviados_em'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['data', 'hora_inicio'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
